//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChudoObuv
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProducts
    {
        public int OrderID { get; set; }
        public int PostionID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual ProductItems ProductItems { get; set; }
    }
}
