//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChudoObuv
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductItems()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int PositionID { get; set; }
        public int ProductID { get; set; }
        public int SizeID { get; set; }
        public int QuantityInStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual Products Products { get; set; }
        public virtual Sizes Sizes { get; set; }
    }
}
