//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChudoObuv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductItems = new HashSet<ProductItems>();
        }
    
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get { return Category.CategoryName; } }
        public int SubcategoryID { get; set; }
        public string SubcategoryName { get { return Subcategory.SubcategoryName; } }
        public string Image { get; set; }
        public string ImagePath { get { return "Images/" + Image; } }
        public string ProductName { get; set; }
        public int ManufactureID { get; set; }
        public string ManufactureName { get { return Manufacture.ManufactureName; } }
        public string Description { get; set; }
        public string Structure { get; set; }
        public double Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductItems> ProductItems { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
}
